<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.sw.ck</groupId>
        <artifactId>smart-workflow</artifactId>
        <version>0.1.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>sw-biz-form</artifactId>
    <packaging>pom</packaging>

    <name>Smart-WorkFlow :: Biz :: Form</name>
    <description>低代码表单模块：设计器/控件/表单管理/规则/数据/数据源/打印</description>

    <modules>
        <module>sw-biz-form-api</module>
        <module>sw-biz-form-biz</module>
    </modules>
</project>
