<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.sw.ck</groupId>
        <artifactId>smart-workflow</artifactId>
        <version>${revision}</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>sw-basic-job</artifactId>
    <packaging>pom</packaging>

    <name>Smart-WorkFlow :: Basic :: Job</name>
    <description>定时任务调度模块父 POM（Quartz 单节点 / BEAN / FLOW 两种任务类型）</description>

    <modules>
        <module>sw-basic-job-api</module>
        <module>sw-basic-job-biz</module>
    </modules>
</project>
