<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.sw.ck</groupId>
        <artifactId>smart-workflow</artifactId>
        <version>${revision}</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>sw-basic-storage</artifactId>
    <packaging>pom</packaging>

    <name>Smart-WorkFlow :: Basic :: Storage</name>
    <description>文件存储模块父 POM（多向可配置：本地 / MinIO / COS / 七牛云）</description>

    <modules>
        <module>sw-basic-storage-api</module>
        <module>sw-basic-storage-biz</module>
    </modules>
</project>
