<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.sw.ck</groupId>
        <artifactId>smart-workflow</artifactId>
        <version>0.1.0</version>
    </parent>

    <artifactId>sw-framework</artifactId>
    <packaging>pom</packaging>

    <name>Smart-WorkFlow :: Framework</name>
    <description>内核层：公共基础设施 + 认证鉴权</description>

    <modules>
        <module>sw-common</module>
        <module>sw-security</module>
    </modules>
</project>
