<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.sw.ck</groupId>
        <artifactId>smart-workflow</artifactId>
        <version>0.1.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>sw-biz-system</artifactId>
    <packaging>pom</packaging>

    <name>Smart-WorkFlow :: Biz :: System</name>
    <description>组织架构/权限数据/字典参数/系统运维监控模块</description>

    <modules>
        <module>sw-biz-system-api</module>
        <module>sw-biz-system-biz</module>
    </modules>
</project>
