<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.sw.ck</groupId>
        <artifactId>smart-workflow</artifactId>
        <version>${revision}</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>sw-basic-notify</artifactId>
    <packaging>pom</packaging>

    <name>Smart-WorkFlow :: Basic :: Notify</name>
    <description>站内信 + 系统通知模块：多渠道/模板/规则/发送记录</description>

    <modules>
        <module>sw-basic-notify-api</module>
        <module>sw-basic-notify-biz</module>
    </modules>
</project>
